import { BaseProvider } from "./base.js";
import {
  AnalysisInput,
  AIAnalysisResult,
  AnalysisIssue,
} from "../core/result.js";

/**
 * DummyProvider
 *
 * A deterministic, local provider used for development, testing,
 * and CI bootstrap.
 *
 * It does NOT perform real AI analysis and does NOT call external APIs.
 * Its purpose is to validate the pipeline:
 * adapter → engine → reporter.
 */
export class DummyProvider extends BaseProvider {
  async analyzeCode(input: AnalysisInput): Promise<AIAnalysisResult> {
    const issues: AnalysisIssue[] = [];

    const content = input.content;

    // Very naive heuristics to simulate "AI slop" signals
    if (content.includes("TODO")) {
      issues.push({
        message: "Found TODO comment in code",
        category: "style",
      });
    }

    if (content.includes("FIXME")) {
      issues.push({
        message: "Found FIXME comment in code",
        category: "style",
      });
    }

    if (
      content.toLowerCase().includes("generated by") ||
      content.toLowerCase().includes("as an ai")
    ) {
      issues.push({
        message: "Possible AI-generated boilerplate detected",
        category: "style",
      });
    }

    return {
      issues,
    };
  }
}
