stages:
  - test

.slop_gate_base:
  image: 
    name: ghcr.io/sergudo/ai-slop-gate:latest
    entrypoint: [""] 
  variables:
    SLOP_PATH: $CI_PROJECT_DIR
    SLOP_PROVIDERS: "static"
  interruptible: true
  script:
    - |
      echo "--- AI SLOP GATE STARTING ---"
      
      if [ -f "policy.yml" ]; then
        SELECTED_POLICY="policy.yml"
      else
        SELECTED_POLICY="/app/policy.yml"
      fi
      echo "Using policy: $SELECTED_POLICY"

      ARGS="" 
      IS_LLM=false

      for p in $SLOP_PROVIDERS; do 
        ARGS="$ARGS --provider $p"
        if [[ "$p" == "gemini" || "$p" == "groq" ]]; then
          IS_LLM=true
        fi
      done
      
      if [ "$IS_LLM" = true ]; then
        ARGS="$ARGS --llm-local"
      fi

      echo "DEBUG: Final ARGS are: $ARGS"
      
      ai-slop-gate run --path "$SLOP_PATH" $ARGS --policy "$SELECTED_POLICY"

ai_slop_gate_quick:
  extends: .slop_gate_base
  stage: test
  variables:
    SLOP_PROVIDERS: "static"
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

ai_slop_gate_full:
  extends: .slop_gate_base
  stage: test
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && ($GEMINI_API_KEY || $SLOPE_GATE_GROQ)
      when: on_success
    - if: $CI_PIPELINE_SOURCE == "web"
      when: always